// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imjsedmiqoedrfylskvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltanNlZG1pcW9lZHJmeWxza3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNDE4NjEsImV4cCI6MjA1MTkxNzg2MX0.Ts1RRecyPKA6Ik7ZrgutT2smJ1m_727oN4ezKVWcoGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);